INFO Watching for file changes with StatReloader
INFO "GET / HTTP/1.1" 200 5622
INFO "GET /new_cargo/ HTTP/1.1" 200 5655
INFO "GET /preview_cargos/ HTTP/1.1" 200 4824
ERROR Errors happened
Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/status_logger/status_logger.py", line 16, in wrapper
    res = func(*args, **kwargs)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py", line 47, in ret_cargo
    raise Exception
Exception
INFO "GET /ret_cargo/ HTTP/1.1" 200 1748
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET / HTTP/1.1" 200 5622
ERROR "GET /ret_cargo/ HTTP/1.1" 500 80874
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_backend/settings.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_backend/settings.py changed, reloading.
INFO Watching for file changes with StatReloader
ERROR "GET /ret_cargo/ HTTP/1.1" 500 80934
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_backend/settings.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET / HTTP/1.1" 200 5622
INFO "GET /preview_cargos/ HTTP/1.1" 200 4824
INFO "GET /new_cargo/ HTTP/1.1" 200 5655
INFO "GET /ret_cargo/ HTTP/1.1" 200 3265
INFO "GET /new_cargo/ HTTP/1.1" 200 5655
INFO "GET /preview_cargos/ HTTP/1.1" 200 4824
INFO "GET / HTTP/1.1" 200 5622
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/custom_logic/new_cargo_logic.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/custom_logic/new_cargo_logic.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/custom_logic/new_cargo_logic.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/custom_logic/new_cargo_logic.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/cargos_saving.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_backend/settings.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/custom_logic/new_cargo_logic.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_backend/settings.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_backend/settings.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/custom_logic/new_cargo_logic.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/custom_logic/new_cargo_logic.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/custom_logic/new_cargo_logic.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/custom_logic/new_cargo_logic.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/custom_logic/new_cargo_logic.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/custom_logic/new_cargo_logic.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/custom_logic/new_cargo_logic.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/custom_logic/new_cargo_logic.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/cargos_saving.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
ERROR Errors happened
Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/shared_logic/status_logger/status_logger.py", line 16, in wrapper
    res = func(*args, **kwargs)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py", line 18, in index
    return render(request, 'main_control/controller/control.html', {'form': form})
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 264, in do_extends
    bits[1] = construct_relative_path(parser.origin.template_name, bits[1])
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 239, in construct_relative_path
    "template '%s' is in." % (relative_name, current_template_name)
django.template.exceptions.TemplateSyntaxError: The relative path '"../../../../shared_logic/templates/utils/wrappers/wrapper.html"' points outside the file hierarchy that template 'main_control/controller/control.html' is in.
ERROR "GET / HTTP/1.1" 500 93325
ERROR Errors happened
Traceback (most recent call last):
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: utils/wrappers/wrapper.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/shared_logic/status_logger/status_logger.py", line 16, in wrapper
    res = func(*args, **kwargs)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py", line 18, in index
    return render(request, 'main_control/controller/control.html', {'form': form})
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: utils/wrappers/wrapper.html
ERROR "GET / HTTP/1.1" 500 92349
INFO Watching for file changes with StatReloader
ERROR Errors happened
Traceback (most recent call last):
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: main_control/utils/wrappers/wrapper.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/shared_logic/status_logger/status_logger.py", line 16, in wrapper
    res = func(*args, **kwargs)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py", line 18, in index
    return render(request, 'main_control/controller/control.html', {'form': form})
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: main_control/utils/wrappers/wrapper.html
ERROR "GET / HTTP/1.1" 500 92401
INFO Watching for file changes with StatReloader
ERROR Errors happened
Traceback (most recent call last):
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: utils/wrappers/wrapper.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/shared_logic/status_logger/status_logger.py", line 16, in wrapper
    res = func(*args, **kwargs)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py", line 18, in index
    return render(request, 'main_control/controller/control.html', {'form': form})
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: utils/wrappers/wrapper.html
ERROR "GET / HTTP/1.1" 500 92349
INFO Watching for file changes with StatReloader
ERROR Errors happened
Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/shared_logic/status_logger/status_logger.py", line 16, in wrapper
    res = func(*args, **kwargs)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py", line 18, in index
    return render(request, 'main_control/controller/control.html', {'form': form})
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 264, in do_extends
    bits[1] = construct_relative_path(parser.origin.template_name, bits[1])
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 239, in construct_relative_path
    "template '%s' is in." % (relative_name, current_template_name)
django.template.exceptions.TemplateSyntaxError: The relative path '"../../../utils/wrappers/wrapper.html"' points outside the file hierarchy that template 'main_control/controller/control.html' is in.
ERROR "GET / HTTP/1.1" 500 93169
INFO Watching for file changes with StatReloader
ERROR Errors happened
Traceback (most recent call last):
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: utils/wrappers/wrapper.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/shared_logic/status_logger/status_logger.py", line 16, in wrapper
    res = func(*args, **kwargs)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py", line 18, in index
    return render(request, 'main_control/controller/control.html', {'form': form})
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: utils/wrappers/wrapper.html
ERROR "GET / HTTP/1.1" 500 92349
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_backend/settings.py changed, reloading.
INFO Watching for file changes with StatReloader
ERROR Errors happened
Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/shared_logic/status_logger/status_logger.py", line 16, in wrapper
    res = func(*args, **kwargs)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py", line 18, in index
    return render(request, 'main_control/controller/control.html', {'form': form})
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'sign_out' not found. 'sign_out' is not a valid view function or pattern name.
ERROR "GET / HTTP/1.1" 500 140671
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py changed, reloading.
INFO Watching for file changes with StatReloader
ERROR Errors happened
Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/shared_logic/status_logger/status_logger.py", line 16, in wrapper
    res = func(*args, **kwargs)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py", line 18, in index
    return render(request, 'main_control/controller/control.html', {'form': form})
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'sign_out' not found. 'sign_out' is not a valid view function or pattern name.
ERROR "GET / HTTP/1.1" 500 140671
ERROR Errors happened
Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/shared_logic/status_logger/status_logger.py", line 16, in wrapper
    res = func(*args, **kwargs)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py", line 18, in index
    return render(request, 'main_control/controller/control.html', {'form': form})
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'sign_out' not found. 'sign_out' is not a valid view function or pattern name.
ERROR "GET / HTTP/1.1" 500 140181
ERROR Errors happened
Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/shared_logic/status_logger/status_logger.py", line 16, in wrapper
    res = func(*args, **kwargs)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py", line 18, in index
    return render(request, 'main_control/controller/control.html', {'form': form})
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'sign_out' not found. 'sign_out' is not a valid view function or pattern name.
INFO "GET / HTTP/1.1" 200 1867
ERROR Errors happened
Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/shared_logic/status_logger/status_logger.py", line 16, in wrapper
    res = func(*args, **kwargs)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py", line 18, in index
    return render(request, 'main_control/controller/control.html', {'form': form})
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'sign_out' not found. 'sign_out' is not a valid view function or pattern name.
INFO "GET / HTTP/1.1" 200 1867
INFO Watching for file changes with StatReloader
ERROR Errors happened
Traceback (most recent call last):
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/base.py", line 75, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/shared_logic/status_logger/status_logger.py", line 16, in wrapper
    res = func(*args, **kwargs)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py", line 18, in index
    return render(request, 'main_control/controller/control.html', {'form': form})
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/base.py", line 86, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'users' is not a registered namespace
INFO "GET / HTTP/1.1" 200 1806
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_backend/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/users/views.py changed, reloading.
INFO Watching for file changes with StatReloader
ERROR Errors happened
Traceback (most recent call last):
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/base.py", line 75, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/shared_logic/status_logger/status_logger.py", line 16, in wrapper
    res = func(*args, **kwargs)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py", line 18, in index
    return render(request, 'main_control/controller/control.html', {'form': form})
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/base.py", line 86, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'users' is not a registered namespace
INFO "GET / HTTP/1.1" 200 1806
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_backend/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
ERROR Errors happened
Traceback (most recent call last):
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/base.py", line 75, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/shared_logic/status_logger/status_logger.py", line 16, in wrapper
    res = func(*args, **kwargs)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py", line 18, in index
    return render(request, 'main_control/controller/control.html', {'form': form})
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/base.py", line 86, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'users' is not a registered namespace
INFO "GET / HTTP/1.1" 200 1806
INFO Watching for file changes with StatReloader
ERROR Errors happened
Traceback (most recent call last):
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/base.py", line 75, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/shared_logic/status_logger/status_logger.py", line 16, in wrapper
    res = func(*args, **kwargs)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py", line 18, in index
    return render(request, 'main_control/controller/control.html', {'form': form})
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/base.py", line 86, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'users' is not a registered namespace
INFO "GET / HTTP/1.1" 200 1806
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_backend/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/users/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
ERROR Errors happened
Traceback (most recent call last):
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/base.py", line 75, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/shared_logic/status_logger/status_logger.py", line 16, in wrapper
    res = func(*args, **kwargs)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_main/views.py", line 18, in index
    return render(request, 'main_control/controller/control.html', {'form': form})
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/stepan/anaconda3/envs/cargos_backend/lib/python3.6/site-packages/django/urls/base.py", line 86, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'users' is not a registered namespace
INFO "GET / HTTP/1.1" 200 1806
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/users/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/users/urls.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET / HTTP/1.1" 200 5628
INFO "GET / HTTP/1.1" 200 5628
INFO "GET / HTTP/1.1" 200 5628
INFO "GET /preview_cargos/ HTTP/1.1" 200 4830
INFO "GET /new_cargo/ HTTP/1.1" 200 5661
INFO "GET /ret_cargo/ HTTP/1.1" 200 3271
INFO "GET /new_cargo/ HTTP/1.1" 200 5661
INFO "GET /admin/ HTTP/1.1" 200 7651
INFO "GET /admin/ HTTP/1.1" 200 7651
INFO "GET / HTTP/1.1" 200 5628
INFO "GET /new_cargo/ HTTP/1.1" 200 5661
INFO "GET /preview_cargos/ HTTP/1.1" 200 4830
INFO "GET /preview_cargos/4/ HTTP/1.1" 200 4183
INFO "GET /preview_cargos/4 HTTP/1.1" 301 0
INFO "GET /preview_cargos/4/ HTTP/1.1" 200 4183
ERROR "GET /update_cargo/4/ HTTP/1.1" 500 141060
INFO Watching for file changes with StatReloader
INFO "GET /update_cargo/4/ HTTP/1.1" 200 4327
INFO "POST /update_cargo/4/ HTTP/1.1" 302 0
INFO "GET /preview_cargos/ HTTP/1.1" 200 4829
INFO "GET /preview_cargos/?page=2 HTTP/1.1" 200 4467
INFO "GET /preview_cargos/?page=1 HTTP/1.1" 200 4829
INFO "GET /preview_cargos/3/ HTTP/1.1" 200 4193
INFO "GET /update_cargo/3/ HTTP/1.1" 200 4337
INFO "POST /update_cargo/3/ HTTP/1.1" 302 0
INFO "GET /preview_cargos/ HTTP/1.1" 200 4852
INFO "GET / HTTP/1.1" 200 5628
INFO "GET /preview_cargos/ HTTP/1.1" 200 4852
INFO "GET /new_cargo/ HTTP/1.1" 200 5661
INFO "GET /ret_cargo/ HTTP/1.1" 200 3271
INFO "GET /new_cargo/ HTTP/1.1" 200 5661
INFO "GET /users/signOut/ HTTP/1.1" 200 2344
INFO "GET /users/signIn/ HTTP/1.1" 200 3325
INFO "POST /users/signIn/ HTTP/1.1" 302 0
INFO "GET / HTTP/1.1" 200 5628
INFO "GET /users/signOut/ HTTP/1.1" 200 2344
INFO "GET /users/signIn/ HTTP/1.1" 200 3325
INFO "POST /users/signIn/ HTTP/1.1" 200 3475
INFO "POST /users/signIn/ HTTP/1.1" 302 0
INFO "GET / HTTP/1.1" 200 5628
INFO /home/stepan/PycharmProjects/cargos_backend/cargos_backend/cargos_backend/settings.py changed, reloading.
INFO Watching for file changes with StatReloader
INFO "GET / HTTP/1.1" 200 5628
